from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import tomllib

from archpack.core import ArchpackError, destination_for, validate_relative_path


MAX_LOCAL_RULE_LINES = 30


class AgentsPluginError(ArchpackError):
    pass


@dataclass(frozen=True)
class AgentRuleBlock:
    directory: Path
    rules: tuple[str, ...]


@dataclass(frozen=True)
class AgentsResult:
    written: tuple[Path, ...]
    skipped: tuple[Path, ...]


def load_agent_rules(pack_dir: Path) -> list[AgentRuleBlock]:
    config_path = Path(pack_dir) / "agents.toml"
    if not config_path.exists():
        raise AgentsPluginError(f"Missing agents.toml: {config_path}")
    try:
        data = tomllib.loads(config_path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise AgentsPluginError(f"Invalid agents.toml: {exc}") from exc
    raw_blocks = data.get("agents")
    if not isinstance(raw_blocks, list):
        raise AgentsPluginError("agents.toml must define [[agents]] blocks")

    blocks: list[AgentRuleBlock] = []
    seen_dirs: set[str] = set()
    for index, raw in enumerate(raw_blocks):
        if not isinstance(raw, dict):
            raise AgentsPluginError(f"agents block must be a table: index {index}")
        raw_dir = raw.get("dir")
        raw_rules = raw.get("rules")
        if not isinstance(raw_dir, str) or not raw_dir:
            raise AgentsPluginError(f"agents block needs a non-empty dir: index {index}")
        if not isinstance(raw_rules, list) or not all(isinstance(rule, str) for rule in raw_rules):
            raise AgentsPluginError(f"agents block needs string rules: index {index}")
        if not raw_rules:
            raise AgentsPluginError(f"agents block needs at least one rule: index {index}")
        if len(raw_rules) > MAX_LOCAL_RULE_LINES:
            raise AgentsPluginError(
                f"agents block has too many rules: index {index}; max {MAX_LOCAL_RULE_LINES}"
            )
        for rule in raw_rules:
            if not rule.strip():
                raise AgentsPluginError(f"agents block has an empty rule: index {index}")
            if "\n" in rule or "\r" in rule:
                raise AgentsPluginError(f"agents rules must be one line each: index {index}")

        directory = normalize_agent_dir(raw_dir)
        dir_key = directory.as_posix()
        if dir_key in seen_dirs:
            raise AgentsPluginError(f"duplicate agents dir: {dir_key}")
        seen_dirs.add(dir_key)
        blocks.append(AgentRuleBlock(directory, tuple(rule.strip() for rule in raw_rules)))
    return blocks


def normalize_agent_dir(raw_dir: str) -> Path:
    directory = Path(raw_dir)
    if raw_dir == ".":
        return Path(".")
    validate_relative_path(directory)
    return directory


def is_ancestor_or_self(parent: Path, child: Path) -> bool:
    if parent == Path("."):
        return True
    parent_parts = parent.parts
    child_parts = child.parts
    return child_parts[: len(parent_parts)] == parent_parts


def effective_blocks_for(target: AgentRuleBlock, blocks: list[AgentRuleBlock]) -> list[AgentRuleBlock]:
    inherited = [block for block in blocks if is_ancestor_or_self(block.directory, target.directory)]
    return sorted(inherited, key=lambda block: (0 if block.directory == Path(".") else len(block.directory.parts)))


def render_agents_md(blocks: list[AgentRuleBlock]) -> str:
    lines = [
        "# AGENTS.md",
        "",
        "Generated by Archpack agents plugin.",
        "Source of truth: agents.toml.",
        "Edit agents.toml and regenerate this file; do not edit generated AGENTS.md files directly.",
        "",
    ]
    for block in blocks:
        label = "." if block.directory == Path(".") else block.directory.as_posix()
        lines.extend([f"## Rules from `{label}`", ""])
        lines.extend(f"- {rule}" for rule in block.rules)
        lines.append("")
    return "\n".join(lines)


def generate_agents(pack_dir: Path, out_dir: Path, *, overwrite: bool = False) -> AgentsResult:
    written: list[Path] = []
    skipped: list[Path] = []
    blocks = load_agent_rules(pack_dir)
    for block in blocks:
        rel = block.directory / "AGENTS.md"
        dest = destination_for(Path(out_dir), rel)
        if dest.exists() and not overwrite:
            skipped.append(rel)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render_agents_md(effective_blocks_for(block, blocks)), encoding="utf-8")
        written.append(rel)
    return AgentsResult(tuple(written), tuple(skipped))
