from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import tomllib

from archpack.core import ArchpackError, UnsafePathError, destination_for, validate_relative_path


MAX_LOCAL_RULE_LINES = 30


class AgentsPluginError(ArchpackError):
    pass


@dataclass(frozen=True)
class AgentRuleBlock:
    directory: Path
    rules: tuple[str, ...]


@dataclass(frozen=True)
class AgentsResult:
    written: tuple[Path, ...]
    skipped: tuple[Path, ...]


def load_agent_rules(pack_dir: Path) -> list[AgentRuleBlock]:
    config_path = Path(pack_dir) / "agents.toml"
    if not config_path.exists():
        raise AgentsPluginError(f"Missing agents.toml: {config_path}")
    try:
        data = tomllib.loads(config_path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise AgentsPluginError(f"Invalid agents.toml: {exc}") from exc
    raw_blocks = data.get("agents")
    if not isinstance(raw_blocks, list):
        raise AgentsPluginError("agents.toml must define [[agents]] blocks")

    blocks: list[AgentRuleBlock] = []
    seen_dirs: set[str] = set()
    for index, raw in enumerate(raw_blocks):
        if not isinstance(raw, dict):
            raise AgentsPluginError(f"agents block must be a table: index {index}")
        raw_dir = raw.get("dir")
        raw_rules = raw.get("rules")
        if not isinstance(raw_dir, str) or not raw_dir:
            raise AgentsPluginError(f"agents block needs a non-empty dir: index {index}")
        if not isinstance(raw_rules, list) or not all(isinstance(rule, str) for rule in raw_rules):
            raise AgentsPluginError(f"agents block needs string rules: index {index}")
        if not raw_rules:
            raise AgentsPluginError(f"agents block needs at least one rule: index {index}")
        if len(raw_rules) > MAX_LOCAL_RULE_LINES:
            raise AgentsPluginError(
                f"agents block has too many rules: index {index}; max {MAX_LOCAL_RULE_LINES}"
            )
        for rule in raw_rules:
            if not rule.strip():
                raise AgentsPluginError(f"agents block has an empty rule: index {index}")
            if "\n" in rule or "\r" in rule:
                raise AgentsPluginError(f"agents rules must be one line each: index {index}")

        directory = normalize_agent_dir(raw_dir)
        dir_key = directory.as_posix()
        if dir_key in seen_dirs:
            raise AgentsPluginError(f"duplicate agents dir: {dir_key}")
        seen_dirs.add(dir_key)
        blocks.append(AgentRuleBlock(directory, tuple(rule.strip() for rule in raw_rules)))
    return blocks


def normalize_agent_dir(raw_dir: str) -> Path:
    if raw_dir == ".":
        return Path(".")
    directory = Path(raw_dir)
    try:
        validate_relative_path(directory, raw=raw_dir)
    except UnsafePathError as exc:
        raise AgentsPluginError(str(exc)) from exc
    return directory


def parent_agents_reference(directory: Path) -> str | None:
    if directory == Path("."):
        return None
    return "../AGENTS.md"


def render_agents_md(block: AgentRuleBlock) -> str:
    label = "." if block.directory == Path(".") else block.directory.as_posix()
    lines = [
        "# AGENTS.md",
        "",
        "Generated by Archpack agents plugin.",
        "Source of truth: agents.toml.",
        "Edit agents.toml and regenerate this file; do not edit generated AGENTS.md files directly.",
        "",
    ]
    parent_reference = parent_agents_reference(block.directory)
    if parent_reference is None:
        lines.extend(
            [
                "## Navigation",
                "",
                "When working in a nested directory, read each AGENTS.md on the path from repository root to the target directory.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Navigation",
                "",
                "Read parent guidance first:",
                "",
                f"- `{parent_reference}`",
                "",
            ]
        )
    lines.extend([f"## Local rules for `{label}`", ""])
    lines.extend(f"- {rule}" for rule in block.rules)
    lines.append("")
    return "\n".join(lines)


def generate_agents(pack_dir: Path, out_dir: Path, *, overwrite: bool = False) -> AgentsResult:
    written: list[Path] = []
    skipped: list[Path] = []
    blocks = load_agent_rules(pack_dir)
    for block in blocks:
        rel = Path((block.directory / "AGENTS.md").as_posix())
        dest = destination_for(Path(out_dir), rel)
        if dest.exists() and not overwrite:
            skipped.append(rel)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render_agents_md(block), encoding="utf-8")
        written.append(rel)
    return AgentsResult(tuple(written), tuple(skipped))
