from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import tomllib

from archpack.core import ArchpackError, destination_for


class AgentsPluginError(ArchpackError):
    pass


@dataclass(frozen=True)
class AgentRuleBlock:
    directory: Path
    rules: tuple[str, ...]


@dataclass(frozen=True)
class AgentsResult:
    written: tuple[Path, ...]
    skipped: tuple[Path, ...]


def load_agent_rules(pack_dir: Path) -> list[AgentRuleBlock]:
    config_path = Path(pack_dir) / "agents.toml"
    if not config_path.exists():
        raise AgentsPluginError(f"Missing agents.toml: {config_path}")
    data = tomllib.loads(config_path.read_text(encoding="utf-8"))
    raw_blocks = data.get("agents")
    if not isinstance(raw_blocks, list):
        raise AgentsPluginError("agents.toml must define [[agents]] blocks")

    blocks: list[AgentRuleBlock] = []
    for index, raw in enumerate(raw_blocks):
        if not isinstance(raw, dict):
            raise AgentsPluginError(f"agents block must be a table: index {index}")
        raw_dir = raw.get("dir")
        raw_rules = raw.get("rules")
        if not isinstance(raw_dir, str) or not raw_dir:
            raise AgentsPluginError(f"agents block needs a non-empty dir: index {index}")
        if not isinstance(raw_rules, list) or not all(isinstance(rule, str) for rule in raw_rules):
            raise AgentsPluginError(f"agents block needs string rules: index {index}")
        if not raw_rules:
            raise AgentsPluginError(f"agents block needs at least one rule: index {index}")
        blocks.append(AgentRuleBlock(Path(raw_dir), tuple(raw_rules)))
    return blocks


def render_agents_md(rules: tuple[str, ...]) -> str:
    lines = ["# AGENTS.md", "", "Generated by Archpack agents plugin.", "", "## Rules", ""]
    lines.extend(f"- {rule}" for rule in rules)
    lines.append("")
    return "\n".join(lines)


def generate_agents(pack_dir: Path, out_dir: Path, *, overwrite: bool = False) -> AgentsResult:
    written: list[Path] = []
    skipped: list[Path] = []
    for block in load_agent_rules(pack_dir):
        rel = block.directory / "AGENTS.md"
        dest = destination_for(Path(out_dir), rel)
        if dest.exists() and not overwrite:
            skipped.append(rel)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render_agents_md(block.rules), encoding="utf-8")
        written.append(rel)
    return AgentsResult(tuple(written), tuple(skipped))
